[package]
name = "tsctimer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
crossterm = "0.29.0"
rand = "0.9.1"
ratatui = "0.29.0"
csv = "1.3.1"
dirs = "6.0.0"
rodio = { version = "0.20.1", default-features = false }
